/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.api.gestorproyectossimple.GestorProyectosSimpleApplication;
import org.junit.jupiter.api.Test;

class GestorProyectoSimpleApplicationTest {
    @Test void appHasAGreeting() {
        GestorProyectosSimpleApplication classUnderTest = new GestorProyectosSimpleApplication();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
